# Generated by Django 5.1.5 on 2025-02-05 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Farm id')),
                ('owner', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre productor')),
                ('region', models.CharField(blank=True, max_length=200, null=True, verbose_name='Región/ Zona o cooperativa')),
                ('municipio', models.CharField(blank=True, max_length=500, null=True, verbose_name='Municipio')),
                ('departamento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='SubFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(blank=True, max_length=1, null=True)),
                ('technical', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tecnico')),
                ('map_date', models.DateField()),
                ('region', models.CharField(blank=True, max_length=200, null=True, verbose_name='Region')),
                ('nom_pol', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom_pol')),
                ('area_pol', models.FloatField(blank=True, max_length=200, null=True, verbose_name='area_pol')),
                ('latitude', models.CharField(blank=True, max_length=200, null=True, verbose_name='latitud')),
                ('longitude', models.CharField(blank=True, max_length=200, null=True, verbose_name='longitud')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_subfarms', to='myapp.farm', verbose_name='farm')),
            ],
            options={
                'unique_together': {('farm', 'sub_name')},
            },
        ),
        migrations.CreateModel(
            name='ERDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.BooleanField(verbose_name='At Risk of Deforestation')),
                ('sub_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_erda', to='myapp.subfarm', verbose_name='sub_farm')),
            ],
        ),
        migrations.CreateModel(
            name='Deforestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=500, verbose_name='Nivel riesgo deforestación desde oficina')),
                ('fase', models.CharField(max_length=500, verbose_name='Fase')),
                ('sub_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_deforestation', to='myapp.subfarm', verbose_name='sub_farm')),
            ],
        ),
    ]
