# Generated by Django 5.1.5 on 2025-02-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfarm',
            name='map_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
