# Generated by Django 5.1.5 on 2025-02-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_subfarm_map_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='erda',
            name='polygon_source',
            field=models.CharField(default='', max_length=500, verbose_name='Polygono Source'),
            preserve_default=False,
        ),
    ]
