# Generated by Django 5.1.5 on 2025-02-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_erda_polygon_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='erda',
            name='area_pol',
            field=models.FloatField(blank=True, max_length=200, null=True, verbose_name='area_pol'),
        ),
    ]
